# ---- Base ----
FROM node:22-alpine AS base
WORKDIR /app
COPY package.json .

# Development
FROM base AS development
RUN npm install
COPY . .
CMD ["npm", "run", "dev", "--", "--host"]


# Production build 
FROM base AS build
RUN npm install
COPY . .
RUN npm run build

# Production 
FROM nginx:stable-alpine AS production
COPY --from=build /app/dist /usr/share/nginx/html
COPY /nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]