services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  express-app:
    container_name: express-app-container
    build:
      context: backend/.
      target: development
    volumes:
      - ./backend:/app:ro
    ports:
      - "3500:3500"
    env_file:
      - backend/.env
    depends_on:
      - db
    
  frontend:
    container_name: frontend-app-container
    build: 
      context: frontend/.
      target: development
    ports:
    - "5173:5173"
    volumes:
      - ./frontend:/app:ro
      - /app/node_modules
    depends_on:
    - express-app


  ml-service:
    container_name: ml-service-container
    build:
      context: ml-service/.
    volumes:
      - ./ml-service:/ml-service:ro
    depends_on:
      - express-app


volumes:
  pgdata: