# ---- Base ----
FROM node:22-alpine AS base
WORKDIR /app
COPY package.json .

#development 
FROM base as development 
RUN  npm install

COPY . .


CMD [ "npm", "run", "dev" ]

#production 
FROM base as production

RUN npm install --only=production

COPY . .

EXPOSE 3500

CMD [ "npm", "start" ]



